apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: de-labs
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://localhost:30901"
        - name: MINIO_SERVER_URL
          value: "http://localhost:30900"
        - name: MINIO_BROWSER
          value: "on"
        - name: MINIO_DOMAIN
          value: "localhost"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: storage
          mountPath: "/data"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: de-labs
spec:
  type: NodePort
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    nodePort: 30900
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 30901
    protocol: TCP
  selector:
    app: minio