apiVersion: v1
kind: Service
metadata:
  name: spark-operator
  namespace: de-labs
spec:
  ports:
  - name: metrics
    port: 10254
    targetPort: 10254
  - name: webhook
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spark-operator
  type: ClusterIP