apiVersion: v1          # API version for the Service resource
kind: Service           # Kubernetes resource type - Service
metadata:
  name: minio-console-lb  # Name of the service
  namespace: de-labs      # Kubernetes namespace where this service is deployed
spec:
  type: LoadBalancer    # Service type - uses MetalLB to assign an external IP
  ports:
    - name: http        # Name of the port
      port: 30000          # Port exposed by the service
      targetPort: 9443  # Port on the pods that the service forwards to (MinIO console port)
  selector:             # Labels used to select which pods to route traffic to
    v1.min.io/tenant: minio-tenant-1        # Selects pods with this tenant label
    v1.min.io/console: minio-tenant-1-console  # Selects pods with this console label